{
 "title": "libvirt-exporter1",
 "description": "generic dashboard for libvirt_exporter ",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "domain", "query": "label_values(domain)" },
   { "name": "target_device", "label": "target_device", "query": "label_values(target_device)" }
  ]
 },
 "panels": [
  {
   "title": "libvirt_domain_cpu_util",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_cpu_stats_cpu_time_nanosecs{domain=~\"$domain\"} [5m])* 100 / 1000000000"
    }
   ]
  },
  {
   "title": "mem_utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(libvirt_mem_stats_available{domain=~\"$domain\"} - libvirt_mem_stats_unused{domain=~\"$domain\"}) /libvirt_mem_stats_available{domain=~\"$domain\"}"
    }
   ]
  },
  {
   "title": "write_requests_issued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, job)(rate(libvirt_block_stats_write_requests_issued{domain=~\"$domain\"}[10s]))"
    }
   ]
  },
  {
   "title": "read_requests_issued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, job)(rate(libvirt_block_stats_read_requests_issued{domain=~\"$domain\"}[10s]))"
    }
   ]
  },
  {
   "title": "stats_write_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum without (instance,job)(rate(libvirt_block_stats_write_bytes{domain=~\"$domain\"}[10s]))"
    }
   ]
  },
  {
   "title": "stats_read_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum without (instance,job)(rate(libvirt_block_stats_read_bytes{domain=~\"$domain\"}[10s]))"
    }
   ]
  },
  {
   "title": "interface_read_packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance,job)(rate(libvirt_interface_read_packets{domain=~\"$domain\"}[10s]))"
    }
   ]
  },
  {
   "title": "interface_write_packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance,job)(rate(libvirt_interface_write_packets{domain=~\"$domain\"}[10s]))"
    }
   ]
  },
  {
   "title": "interface_read_bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, job)(rate(libvirt_interface_read_bytes{domain=~\"$domain\"}[10s]))"
    }
   ]
  },
  {
   "title": "interface_write_bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, job)(rate(libvirt_interface_write_bytes{domain=~\"$domain\"}[10s]))"
    }
   ]
  },
  {
   "title": "libvirt_domain_cpu_stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "libvirt_cpu_stats_system_time_nanosecs{domain=~\"$domain\"} "
    },
    {
     "expr": "libvirt_cpu_stats_cpu_time_nanosecs{domain=~\"$domain\"} "
    },
    {
     "expr": "libvirt_cpu_stats_user_time_nanosecs{domain=~\"$domain\"}"
    }
   ]
  }
 ]
}