{
 "title": "Pushgateway Windows Desktop Overview",
 "description": "A dashboard for monitoring a Windows Desktop/Gaming PC. Using Prometheus, wmi_exporter, and OhmGraphite.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "push_job",
    "label": "Pushgateway Job",
    "query": "label_values(wmi_system_system_up_time, job)"
   },
   {
    "name": "pushgateway",
    "label": "Pushgateway",
    "query": "label_values(wmi_system_system_up_time{job=~\"$push_job\"}, instance)"
   },
   {
    "name": "node",
    "label": "Exported Instance",
    "query": "label_values(wmi_system_system_up_time{job=~\"$push_job\"}, exported_instance)"
   },
   {
    "name": "job_node",
    "label": "Exported Job",
    "query": "label_values(wmi_system_system_up_time{job=~\"$push_job\"}, exported_job)"
   }
  ]
 },
 "panels": [
  { "title": "Current Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by (exported_instance) (irate(wmi_cpu_time_total{mode=\"idle\", exported_instance=~\"$node\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(wmi_cs_physical_memory_bytes{exported_instance=~\"$node\"} - wmi_os_physical_memory_free_bytes{exported_instance=~\"$node\"}) / wmi_cs_physical_memory_bytes{exported_instance=~\"$node\"} * 100"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(irate(wmi_net_bytes_total{exported_instance=\"$node\"}[1m])) > 1)* 8"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(wmi_logical_disk_size_bytes{volume!~\"Harddisk.*\", exported_instance=\"$node\"}) by (exported_instance) - sum(wmi_logical_disk_free_bytes{volume!~\"Harddisk.*\", exported_instance=\"$node\"}) by (exported_instance)) / sum(wmi_logical_disk_size_bytes{volume!~\"Harddisk.*\", exported_instance=\"$node\"}) by (exported_instance) * 100"
    }
   ]
  },
  {
   "title": "GPU Core Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nvidiagpu_0_load_0)" }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(intelcpu_0_temperature_0) + sum(intelcpu_0_temperature_1) + sum(intelcpu_0_temperature_2) + sum(intelcpu_0_temperature_3) + sum(intelcpu_0_temperature_4) + sum(intelcpu_0_temperature_5) + sum(intelcpu_0_temperature_6) + sum(intelcpu_0_temperature_7)) / 8"
    },
    {}
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "nvidiagpu_0_temperature_0{host=\"SETH-PC\"}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg without (cpu) (sum(irate(wmi_cpu_time_total{exported_instance=\"$node\",mode!=\"idle\"}[5m])) by (mode)) / 8)* 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "wmi_cs_physical_memory_bytes{exported_instance=\"$node\"} - wmi_os_physical_memory_free_bytes{exported_instance=\"$node\"}",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "wmi_cs_physical_memory_bytes{exported_instance=\"$node\"}",
     "legendFormat": "Total Memory"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "sum(nvidiagpu_0_load_0)", "legendFormat": "GPU Core" },
    { "expr": "sum(nvidiagpu_0_load_1)", "legendFormat": "GPU Memory Controller" },
    { "expr": "sum(nvidiagpu_0_load_2)", "legendFormat": "GPU Video Engine" },
    { "expr": "sum(nvidiagpu_0_load_3)", "legendFormat": "GPU Memory" }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(wmi_net_bytes_received_total{exported_instance=~\"$node\",exported_job=~\"$job_node\"}[1m])) by (exported_instance) > 1)* 8",
     "legendFormat": "Received"
    },
    {
     "expr": "(sum(irate(wmi_net_bytes_sent_total{exported_instance=\"$node\",exported_job=\"$job_node\"}[1m])) by (exported_instance) > 1)* 8",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Bandwidth Usage (Hourly)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(wmi_net_bytes_received_total{exported_instance=\"$node\"}[1h])) by (exported_instance)",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(increase(wmi_net_bytes_sent_total{exported_instance=\"$node\"}[1h])) by (exported_instance)",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Bandwidth Usage (Daily)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(wmi_net_bytes_received_total{exported_instance=\"$node\"}[1h])) by (exported_instance)",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(increase(wmi_net_bytes_sent_total{exported_instance=\"$node\"}[1h])) by (exported_instance)",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Free Space",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "wmi_logical_disk_free_bytes{exported_instance=\"$node\", volume !~\"HarddiskVolume.+\"}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(wmi_logical_disk_split_ios_total{exported_instance=~\"$node\", volume !~\"HarddiskVolume.+\"}[1m])",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Reads/Writes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(wmi_logical_disk_write_bytes_total{exported_instance=\"$node\", volume !~\"HarddiskVolume.+\"}[1m])",
     "legendFormat": "{{volume}} - Writes"
    },
    {
     "expr": "irate(wmi_logical_disk_read_bytes_total{exported_instance=\"$node\", volume !~\"HarddiskVolume.+\"}[1m])",
     "legendFormat": "{{volume}} - Reads"
    }
   ]
  },
  { "title": "Processes / Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "# of Processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wmi_os_processes{exported_instance=~\"$node\",exported_job=~\"$job_node\"}",
     "legendFormat": "Processes"
    }
   ]
  },
  {
   "title": "Services",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(wmi_service_state{exported_instance=~\"$node\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(wmi_service_status{exported_instance=\"$node\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "GPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      { "expr": "nvidiagpu_0_smalldata_2", "legendFormat": "Used Memory" },
      { "expr": "nvidiagpu_0_smalldata_3", "legendFormat": "Total Memory" }
     ]
    },
    {
     "title": "Clock Speeds",
     "type": "graph",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 50 },
     "yaxes": [
      { "format": "none", "label": "MHz" }
     ],
     "targets": [
      { "expr": "nvidiagpu_0_clock_0", "legendFormat": "GPU Core" },
      { "expr": "nvidiagpu_0_clock_1", "legendFormat": "GPU Memory" },
      { "expr": "nvidiagpu_0_clock_2", "legendFormat": "GPU Shader" }
     ]
    },
    {
     "title": "Power",
     "type": "graph",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 50 },
     "yaxes": [
      { "format": "watt" }
     ],
     "targets": [
      { "expr": "nvidiagpu_0_power_0", "legendFormat": "Power" }
     ]
    }
   ]
  },
  {
   "title": "Tempatures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Temperatures",
     "type": "graph",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "intelcpu_0_temperature_0", "legendFormat": "Core #1" },
      { "expr": "intelcpu_0_temperature_1", "legendFormat": "Core #2" },
      { "expr": "intelcpu_0_temperature_2", "legendFormat": "Core #3" },
      { "expr": "intelcpu_0_temperature_3", "legendFormat": "Core #4" },
      { "expr": "intelcpu_0_temperature_4", "legendFormat": "Core #5" },
      { "expr": "intelcpu_0_temperature_5", "legendFormat": "Core #6" },
      { "expr": "intelcpu_0_temperature_6", "legendFormat": "Core #7" },
      { "expr": "intelcpu_0_temperature_7", "legendFormat": "Core #8" },
      { "expr": "lpc_nct6797d_temperature_0", "legendFormat": "CPU Package" }
     ]
    },
    {
     "title": "GPU Temperature",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 9, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nvidiagpu_0_temperature_0", "legendFormat": "GPU" }
     ]
    },
    {
     "title": "SSD Temperature",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 15, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "hdd_1_temperature_0", "legendFormat": "Crucial SSD" },
      { "expr": "hdd_2_temperature_0", "legendFormat": "Samsung SSD" }
     ]
    }
   ]
  },
  {
   "title": "Extended CPU Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clock Speeds",
     "type": "graph",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "none", "label": "MHz" }
     ],
     "targets": [
      { "expr": "intelcpu_0_clock_1", "legendFormat": "Core #1" },
      { "expr": "intelcpu_0_clock_2", "legendFormat": "Core #2" },
      { "expr": "intelcpu_0_clock_3", "legendFormat": "Core #3" },
      { "expr": "intelcpu_0_clock_4", "legendFormat": "Core #4" },
      { "expr": "intelcpu_0_clock_5", "legendFormat": "Core #5" },
      { "expr": "intelcpu_0_clock_6", "legendFormat": "Core #6" },
      { "expr": "intelcpu_0_clock_7", "legendFormat": "Core #7" },
      { "expr": "intelcpu_0_clock_8", "legendFormat": "Core #8" }
     ]
    },
    {
     "title": "Power",
     "type": "graph",
     "gridPos": { "h": 10, "w": 10, "x": 11, "y": 52 },
     "yaxes": [
      { "format": "watt" }
     ],
     "targets": [
      { "expr": "intelcpu_0_power_0", "legendFormat": "CPU Package" },
      { "expr": "intelcpu_0_power_1", "legendFormat": "CPU Cores" },
      { "expr": "intelcpu_0_power_2", "legendFormat": "CPU Graphics" },
      { "expr": "intelcpu_0_power_3", "legendFormat": "CPU DRAM" }
     ]
    }
   ]
  }
 ]
}